name: C/C++ CI

on: [push]

jobs:
  build:
    strategy:
      matrix:
        name: [ubuntu, macos, windows]
        include:
          - name: ubuntu
            os: ubuntu-latest
          - name: macos
            os: macos-latest
          - name: windows
            os: windows-latest
    env:
      project-version: "0.1.0"
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Build and Test
        run: |
          mkdir build
          cd build
          cmake .. -DCMAKE_BUILD_TYPE=Release
          cmake --build . --config Release
      - name: Pack (DEB)
        if: startsWith(matrix.os,'ubuntu')
        run: |
          cd build
          cpack -G DEB
      - name: Pack (ZIP)
        if: startsWith(matrix.os,'windows')
        run: |
          cd build
          cmake --version
          cpack.exe -G "ZIP"
      - uses: actions/upload-artifact@v1
        if: startsWith(matrix.os,'ubuntu')
        with:
          name: helloworld-${{env.project-version}}-Linux.deb
          path: build/helloworld-${{env.project-version}}-Linux.deb
